version: 0.2
env:
  secrets-manager:
    LOGIN: finalcasestudy/sonar:sonartoken
    HOST: finalcasestudy/sonar:HOST
    Organization: finalcasestudy/sonar:Organization
    Project: finalcasestudy/sonar:Project
phases:
  build:
    commands:
      - echo Build started 'date'     
      - mvn verify sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = "ERROR" ] ; then exit 1 ;fi
      - gradle build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.war)
      - pwd
artifacts:
  files:
    - 'build/libs/*.war'
    - 'appspec.yml'
    - 'scripts/before_install.sh'
    - 'scripts/after_install.sh'    
    - 'scripts/start_server.sh'
    - 'scripts/stop_server.sh'
